version: '3.4'

services:
  dogbank.ui:
    image: ${DOCKER_REGISTRY-}dogbankui
    build:
        context: .
        dockerfile: src/DogBank.UI/Dockerfile
    networks:
        - dogbanknetwork

  dogbank.api:
    image: ${DOCKER_REGISTRY-}dogbankapi
    build:
        context: .
        dockerfile: src/DogBank.Api/Dockerfile
    ports:
        - 8888:80
    networks:
        - dogbanknetwork
  prometheus:
    build:
        context: ./prometheus
        dockerfile: Dockerfile
        args:
            version: 1
    image: prometheus-local
    restart: always
    ports:
        - 9090:9090
    networks:
        - dogbanknetwork
    volumes:
        - './prometheus/data:/data'
networks: 
    dogbanknetwork:
        driver: bridge
